DROP TABLE `activity_feed`;--> statement-breakpoint
DROP TABLE `channel_messages`;--> statement-breakpoint
DROP TABLE `citizen_post_comments`;--> statement-breakpoint
DROP TABLE `citizen_post_likes`;--> statement-breakpoint
DROP TABLE `citizen_posts`;--> statement-breakpoint
DROP TABLE `communities`;--> statement-breakpoint
DROP TABLE `community_channels`;--> statement-breakpoint
DROP TABLE `community_lobby_alliances`;--> statement-breakpoint
DROP TABLE `community_members`;--> statement-breakpoint
DROP TABLE `constitution_articles`;--> statement-breakpoint
DROP TABLE `contact_submissions`;--> statement-breakpoint
DROP TABLE `content_reports`;--> statement-breakpoint
DROP TABLE `direct_messages`;--> statement-breakpoint
DROP TABLE `forum_comments`;--> statement-breakpoint
DROP TABLE `forum_posts`;--> statement-breakpoint
DROP TABLE `invite_codes`;--> statement-breakpoint
DROP TABLE `lobbies`;--> statement-breakpoint
DROP TABLE `lobby_milestones`;--> statement-breakpoint
DROP TABLE `lobby_plebiscites`;--> statement-breakpoint
DROP TABLE `lobby_supports`;--> statement-breakpoint
DROP TABLE `lobby_timeline`;--> statement-breakpoint
DROP TABLE `moderation_logs`;--> statement-breakpoint
DROP TABLE `moderation_queue`;--> statement-breakpoint
DROP TABLE `national_plebiscite_votes`;--> statement-breakpoint
DROP TABLE `national_plebiscites`;--> statement-breakpoint
DROP TABLE `news_items`;--> statement-breakpoint
DROP TABLE `plebiscite_votes`;--> statement-breakpoint
DROP TABLE `power_metrics`;--> statement-breakpoint
DROP TABLE `press_alerts`;--> statement-breakpoint
DROP TABLE `press_journalists`;--> statement-breakpoint
DROP TABLE `pressure_actions`;--> statement-breakpoint
DROP TABLE `privacy_settings`;--> statement-breakpoint
DROP TABLE `push_tokens`;--> statement-breakpoint
DROP TABLE `smart_milestones`;--> statement-breakpoint
DROP TABLE `user_achievements`;--> statement-breakpoint
DROP TABLE `user_follows`;--> statement-breakpoint
DROP TABLE `user_interactions`;--> statement-breakpoint
DROP TABLE `user_points`;--> statement-breakpoint
DROP TABLE `user_preferences`;--> statement-breakpoint
DROP TABLE `user_profiles`;--> statement-breakpoint
DROP TABLE `users`;